name: LinkedIn Job Alert Bot

on:
  schedule:
    - cron: '0 * * * *'  # Run every hour on the hour
  workflow_dispatch:    # Allow manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies including Playwright browsers
        run: |
          # Removed 'playwright-extra' as it's not a valid pip package name.
          # 'playwright-stealth' works directly with 'playwright'.
          pip install beautifulsoup4 requests playwright playwright-stealth
          playwright install

      - name: Run scraper script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_USER_ID: ${{ secrets.TELEGRAM_USER_ID }}
          LINKEDIN_COOKIES: ${{ secrets.LINKEDIN_COOKIES }}
        run: python job_scraper.py